/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ffb4ab",
        "inverse-primary": "#6d5e00",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#cec6ac",
        "on-primary-container": "#736300",
        "tertiary-fixed-dim": "#00dce1",
        "surface-container-lowest": "#190b03",
        "on-secondary-fixed-variant": "#5e411a",
        "inverse-on-surface": "#3f2c20",
        "secondary-fixed-dim": "#eabf8d",
        "on-tertiary-container": "#006f72",
        "tertiary-container": "#00faff",
        "surface": "#1e1006",
        "on-secondary": "#442b06",
        "surface-container-highest": "#433124",
        "background": "#1e1006",
        "tertiary": "#fbfffe",
        "secondary": "#eabf8d",
        "secondary-container": "#5e411a",
        "on-primary": "#393000",
        "on-secondary-container": "#d7ae7d",
        "surface-tint": "#e2c60f",
        "on-tertiary": "#003738",
        "surface-container": "#2c1c11",
        "surface-container-high": "#38261a",
        "tertiary-fixed": "#2dfaff",
        "on-background": "#fbddca",
        "on-primary-fixed-variant": "#524700",
        "surface-bright": "#483529",
        "surface-variant": "#433124",
        "primary-container": "#ffe135",
        "outline-variant": "#4c4733",
        "primary": "#fffdff",
        "primary-fixed": "#ffe245",
        "on-primary-fixed": "#211b00",
        "surface-container-low": "#28180d",
        "inverse-surface": "#fbddca",
        "on-tertiary-fixed": "#002021",
        "secondary-fixed": "#ffddb7",
        "primary-fixed-dim": "#e2c60f",
        "error-container": "#93000a",
        "outline": "#979179",
        "on-surface": "#fbddca",
        "surface-dim": "#1e1006",
        "on-tertiary-fixed-variant": "#004f51",
        "on-secondary-fixed": "#2a1700",
        "on-error": "#690005"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Space Grotesk", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
